name: "contoso_foo"
author: Tobe O <thosakwe@gmail.com>
homepage: https://regios.dev
version: 0.0.0
environment:
  sdk: ">=2.0.0 <3.0.0"
description: Just a playground
#publish_to: none
dependencies:
  angel_framework: ^2.0.0
  angel_static: ^2.0.0
  http_multi_server: ^2.0.0
  io: ^0.3.2
  #thosakwe.com: ^2.0.0
  # "@thosakwe/foo": ^1.0.0
  # "@thosakwe/bar":
  #   hosted:
  #     name: hey
  #     url: https://pub.regios.dev
